version: '3'

services:
  angular-8-tutorial-app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: 'angular-8-tutorial-app'
    command: sh -c "ng serve --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
      - "9876:9876"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ./app:/app
      - ./app/src:/app/src
      # Use the node_modules folder within our Docker container and NOT the local development environment folder
      - /app/node_modules
    depends_on:
      - angular-8-tutorial-api

  angular-8-tutorial-api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: 'angular-8-tutorial-api'
    # This service will not start until either the mongodb service is available OR thirty seconds have elapsed
    command: sh -c './scripts/wait-for.sh --timeout=30 mongodb:27017 && npx nodemon ./src/server.js -e js,json,graphql'
    ports:
      - "4000:4000"
      - "9229:9229"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ./api:/app
      - ./api/src:/app/src
      # Use the folder(s) within our Docker container and NOT the local development environment folder(s)
      - /app/node_modules
      - /app/scripts
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "angular-8-tutorial-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # If you want to persist MongoDB data after a container has been stopped/deleted, uncomment the volumes section
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "27017:27017"
