version: '3'

services:
  angular-8-tutorial-app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: 'angular-8-tutorial-app'
    command: sh -c "ng serve --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
      - "9876:9876"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ./app:/app
      - ./app/src:/app/src
